project-key: DSB

name: dsb_open_solution
tags: [solution_4, unet-multitask, touching_edges]

metric:
  channel: 'Final Validation Score'
  goal: maximize

#Comment out if not in Cloud Environment
pip-requirements-file: requirements.txt

exclude:
  - output
  - imgs
  - neptune.log
  - offline_job.log
  - .git
  - .idea
  - .ipynb_checkpoints
  - devbook.ipynb
  - morphological_postprocessing.ipynb

parameters:
# Cloud Environment
#  data_dir:                        /public/dsb_2018_data/
#  meta_dir:                        /public/dsb_2018_data/
#  masks_overlayed_dir:             /public/dsb_2018_data/masks_overlayed/
#  contours_overlayed_dir:          /public/dsb_2018_data/contours_overlayed/
#  contours_touching_overlayed_dir: /public/dsb_2018_data/contours_touching_overlayed/
#  centers_overlayed_dir:           /public/dsb_2018_data/centers_overlayed/
#  experiment_dir:                  /output/dsb/experiments/

# Local Environment
  data_dir:                        ../.kaggle/competitions/data-science-bowl-2018/
  meta_dir:                        ../.kaggle/competitions/data-science-bowl-2018/
  masks_overlayed_dir:             ../.kaggle/competitions/data-science-bowl-2018/masks_overlayed/
  contours_overlayed_dir:          ../.kaggle/competitions/data-science-bowl-2018/contours_overlayed/
  contours_touching_overlayed_dir: ../.kaggle/competitions/data-science-bowl-2018/contours_touching_overlayed/
  centers_overlayed_dir:           ../.kaggle/competitions/data-science-bowl-2018/centers_overlayed/
  experiment_dir:                  ../output/dsb/experiments/

  valid_category_ids: '[0, 4]'
  overwrite: 1
  num_workers: 4
  load_in_memory: 1
  pin_memory: 1

# General Params
#  image_h: 512
#  image_w: 512
  image_h: 256
  image_w: 256
  image_channels: 3

# U-Net parameters
  nr_unet_outputs: 4
  n_filters: 16
  conv_kernel: 3
  pool_kernel: 3
  pool_stride: 2
  repeat_blocks: 4

# Training schedule
  epochs_nr: 2
  batch_size_train: 1
  batch_size_inference: 1
  lr: 0.0001
  momentum: 0.9
  gamma: 0.99
  patience: 1

# Regularization
  use_batch_norm: 1
  l2_reg_conv: 0.0001
  l2_reg_dense: 0.0
  dropout_conv: 0.1
  dropout_dense: 0.0

# Postprocessing
  threshold: 0.5
  min_nuclei_size: 20
